audio up: key(volup)
audio down: key(voldown)
set (volume | audio) <number>: user.media_set_volume(number)
(volume | audio | media) mute: key(mute)
[media] play next: key(next)
[media] play previous: key(prev)
media (play | pause | stop): user.play_pause()
